#include "test_util.h"
#include "platform/board.h"

int main(void) {
    ASSERT_EQ(PIN_CC1101_SCLK, 6);
    ASSERT_EQ(PIN_CC1101_MISO, 4);
    ASSERT_EQ(PIN_CC1101_MOSI, 7);
    ASSERT_EQ(PIN_CC1101_CS0, 5);
    ASSERT_EQ(PIN_CC1101_CS1, 18);
    ASSERT_EQ(PIN_CC1101_GDO0_1, 20);
    ASSERT_EQ(PIN_CC1101_GDO0_2, 21);
    ASSERT_EQ(PIN_CC1101_GDO2_1, 22);
    ASSERT_EQ(PIN_CC1101_GDO2_2, 19);

    ASSERT_EQ(PIN_FPGA_CLK, 23);
    ASSERT_EQ(PIN_FPGA_DONE, 24);
    ASSERT_EQ(PIN_FPGA_RESET, 29);

    ASSERT_EQ(PIN_LED, 25);
    ASSERT_EQ(PIN_GUI_NRESET, 28);

    /* Link to display. Same roles as the display side; traces cross. */
    ASSERT_EQ(PIN_LINK_TX, 0);
    ASSERT_EQ(PIN_LINK_RX, 1);
    ASSERT_EQ(PIN_LINK_CTS, 2);
    ASSERT_EQ(PIN_LINK_RTS, 3);

    ASSERT_EQ(PIN_IO_SPI_MISO, 12);
    ASSERT_EQ(PIN_IO_SPI_CS, 13);
    ASSERT_EQ(PIN_IO_SPI_SCLK, 14);
    ASSERT_EQ(PIN_IO_SPI_MOSI, 15);
    ASSERT_EQ(PIN_IO_UART_TX, 8);
    ASSERT_EQ(PIN_IO_UART_RX, 9);
    ASSERT_EQ(PIN_IO_UART_CTS, 10);
    ASSERT_EQ(PIN_IO_UART_RTS, 11);
    ASSERT_EQ(PIN_IO_I2C_SDA, 16);
    ASSERT_EQ(PIN_IO_I2C_SCL, 17);
    ASSERT_EQ(PIN_IO_GPIO_IN, 26);
    ASSERT_EQ(PIN_IO_GPIO_OUT, 27);
    TEST_RETURN();
}
