/* Generated by tools/gen_splash_art.py. */
#ifndef FWOG_SPLASH_ART_H
#define FWOG_SPLASH_ART_H
#include <stdint.h>

#define SPLASH_W        320u
#define SPLASH_H        240u
#define SPLASH_PIXELS   76800u
#define SPLASH_TITLE_X  20u
#define SPLASH_TITLE_Y  168u
#define SPLASH_BOOT_PCM_SAMPLES  0u
#define SPLASH_BOOT_PCM_8BIT     1
#define SPLASH_SHIP_PCM_SAMPLES  23304u
#define SPLASH_SHIP_PCM_8BIT     1

extern const uint16_t splash_image[SPLASH_PIXELS];
extern const uint8_t splash_ship_pcm[SPLASH_SHIP_PCM_SAMPLES];

#endif
