#include "vp_art.h"

/* One hundred relics in the Heroes of Might and Magic cadence: named slot,
 * a tiny bonus, and a story. Tone is Pokemon-pleasant -- wonder, friendship,
 * little legends -- not grimdark. VoltPet lore leans Sonic (speed, loops)
 * and Pikachu (stored sunshine, kind sparks). */

const vp_art_t vp_arts[VP_NART] = {
    {"Boots of Looping Joy", "Boots", "+2 Dash",
     "They tap twice before you notice you have already arrived, grinning."},
    {"Cape of the Blue Blur", "Cape", "+1 Speed",
     "A breeze sewn into cloth. Children race it and always lose, laughing."},
    {"Ring of Open Highways", "Ring", "+1 Dash",
     "Warm as a sunset over a long straight road. It hums when you skip."},
    {"Helm of the Hill Run", "Helm", "+1 Speed",
     "A shepherd wore it to greet every sunrise from a different peak."},
    {"Quills of Tail-Wind", "Relic", "+2 Dash",
     "They whistle a cheerful scale whenever their owner sprints past."},
    {"Sash of Skip-Steps", "Cape", "+1 Speed",
     "Tied by a coach who believed every errand could be a tiny adventure."},
    {"Medal of the Morning Dash", "Relic", "+1 Spark",
     "Awarded to anyone who made it to breakfast before the kettle sang."},
    {"Shoes of Kind Thunder", "Boots", "+2 Dash",
     "Red as a cartoon streak. They never splash a puddle on a friend."},
    {"Band of Echoing Footfalls", "Ring", "+1 Speed",
     "A second pair of steps follows yours, always in time, never late."},
    {"Charm of Almost-Flying", "Necklace", "+1 Dash",
     "It does not lift you. It just reminds your feet they could try."},
    {"Pouches of Stored Sun", "Relic", "+2 Spark",
     "Soft cheek-pockets that glow after a nap in a warm window."},
    {"Cheek-Gems of Cheer", "Necklace", "+1 Spark",
     "Two tiny rubies. They brighten when someone nearby tells a joke."},
    {"Collar of Soft Sparks", "Necklace", "+1 Happy",
     "Static that tickles, never bites. Cats approve, then pretend not to."},
    {"Orb of Pocket Lightning", "Relic", "+2 Spark",
     "A marble that stores one polite zap for opening stubborn jars."},
    {"Gloves of Static Kindness", "Weapon", "+1 Spark",
     "Worn by a baker whose bread rose faster when she hummed."},
    {"Lantern of Happy Current", "Relic", "+1 Spark",
     "It lights the path home and makes moths dance in little circles."},
    {"Pin of the First Zap", "Relic", "+1 Spark",
     "The spark a VoltPet makes when it decides you are its trainer."},
    {"Brooch of Warm Voltage", "Necklace", "+1 Happy",
     "Heats a cold nose. Travelers swear it tastes faintly of citrus."},
    {"Crown of Tiny Thunder", "Helm", "+2 Spark",
     "A child's circlet. Storms that see it turn into summer showers."},
    {"Pendant of Shared Charge", "Necklace", "+1 Spark",
     "Split a spark with a friend and both of you feel braver."},
    {"Necklace of Radio Dew", "Necklace", "+1 Find",
     "Beads that mist over when a quiet carrier wave wanders by."},
    {"Crystal of Kind Frequencies", "Relic", "+2 Find",
     "It chimes when the air is full of messages meant for no one mean."},
    {"Horn of Distant Weather", "Relic", "+1 Find",
     "A weather toy's cousin. It toots for far-off kindness, not alarms."},
    {"Compass of Quiet Carriers", "Relic", "+1 Find",
     "The needle follows songs more faithfully than north."},
    {"Ear-Ring of ISM Song", "Ring", "+1 Find",
     "One earring. The other is still out there, humming along."},
    {"Lens of Hidden Beacons", "Relic", "+2 Find",
     "Look through it and porch lights become lighthouses for a second."},
    {"Drum of Packet Rain", "Weapon", "+1 Find",
     "Tap it and you hear data as a gentle shower on a tin roof."},
    {"Scroll of Whisper Bands", "Relic", "+1 Find",
     "The ink rearranges into callsigns that only want to say hello."},
    {"Fork of Meadow AM", "Weapon", "+1 Find",
     "A tuning fork. Grass seems to keep time when you strike it."},
    {"Amulet of Friendly Noise", "Necklace", "+2 Find",
     "Hiss and crackle that feel like a campfire, not a warning."},
    {"Badge of the First Friend", "Relic", "+2 Happy",
     "Given, never bought. It shines harder the longer you keep showing up."},
    {"Ribbon of Shared Berries", "Cape", "+1 Happy",
     "Tied after a picnic where nobody counted who ate more."},
    {"Hat of Gentle Coaches", "Helm", "+1 Happy",
     "It makes your voice come out like a cheer, even when you whisper."},
    {"Locket of Chosen Bonds", "Necklace", "+2 Happy",
     "Opens only for the person a VoltPet already decided on."},
    {"Scarf of Rainy Walks", "Cape", "+1 Happy",
     "Stays dry on the inside. The outside collects stories instead."},
    {"Bell of Come-Home", "Relic", "+1 Happy",
     "One ring and even the wind remembers which door is yours."},
    {"Map of Picnic Meadows", "Relic", "+1 Find",
     "Blank until you get hungry. Then the nice hills ink themselves in."},
    {"Flask of Pep Talks", "Relic", "+1 Spark",
     "Sip and you hear your own best advice, only kinder."},
    {"Case of Small Wins", "Relic", "+1 Happy",
     "Holds badges for tying shoes, sharing snacks, and trying again."},
    {"Letter of You Are Great", "Relic", "+2 Happy",
     "Unsigned. Every VoltPet believes it was written just for them."},
    {"Basket of Kinetic Berries", "Relic", "+2 Snack",
     "They ripen when you shake the world a little. Tastes like momentum."},
    {"Seed of Sparkfruit", "Relic", "+1 Snack",
     "Plant it in a warm pocket. Harvest is a glow you can share."},
    {"Cup of Song-Snacks", "Relic", "+2 Snack",
     "Fill it by humming. The broth is always the right temperature."},
    {"Spoon of Thunder Honey", "Weapon", "+1 Snack",
     "A drizzle that crackles on the tongue and makes tails wiggle."},
    {"Jar of Radio Jam", "Relic", "+1 Snack",
     "Preserved from a kind signal. Spread it on anything, including courage."},
    {"Leaf of Restful Shade", "Relic", "+2 Energy",
     "One leaf, big as a blanket. Naps beneath it last exactly long enough."},
    {"Stone of Cool Streams", "Relic", "+1 Energy",
     "Hold it and you remember the best drink of water you ever had."},
    {"Bloom of Static Daisies", "Relic", "+1 Happy",
     "They turn to follow cheer instead of the sun. Both work."},
    {"Root of Brave Carrots", "Relic", "+1 Snack",
     "Crunchy. Heroes who eat them still look like themselves, only ruddier."},
    {"Pie of Victory Steam", "Relic", "+2 Snack",
     "The steam spells a tiny 'you did it' before it fades."},
    {"Armor of Dawn's Promise", "Shield", "+2 Guard",
     "Painted the color of almost-morning. Fears politely wait outside."},
    {"Shield of Soft Static", "Shield", "+2 Guard",
     "Sparks hop across it like skip-stones and forget to be scary."},
    {"Blade of Morning Spark", "Weapon", "+2 Spark",
     "Not sharp. It points at problems until they feel solvable."},
    {"Helm of Clear Skies", "Helm", "+1 Guard",
     "Clouds that mean harm wander off to water somebody's garden."},
    {"Spellbinder's Picnic Hat", "Helm", "+1 Happy",
     "Ants attend in an orderly line and leave a thank-you crumb."},
    {"Greaves of the Long Stroll", "Boots", "+1 Energy",
     "Miles feel like blocks. Blisters file a complaint and lose."},
    {"Tome of Friendly Cantrips", "Relic", "+1 Spark",
     "Page one: how to make a spark that looks like a heart."},
    {"Cloak of Quiet Courage", "Cape", "+2 Guard",
     "You still feel nervous. You just remember nervous can come along."},
    {"Gauntlets of Helping Hands", "Weapon", "+1 Happy",
     "They fit whoever needs to carry the extra bag today."},
    {"Banner of Tiny Kingdoms", "Relic", "+1 Happy",
     "A flag for clubs of two: you and your VoltPet, forever chartered."},
    {"Sneakers of Red Lightning", "Boots", "+2 Dash",
     "White stripe, red flash. Puddles applaud when you pass."},
    {"Spikes of Cheerful Rush", "Helm", "+1 Dash",
     "Hair that refuses to lie down. Speed limits smile and wave you on."},
    {"Belt of One More Lap", "Cape", "+1 Energy",
     "A second wind with manners. It asks first, then lifts your feet."},
    {"Goggles of Wind-Smile", "Helm", "+1 Speed",
     "The world looks faster and friendlier through the lenses."},
    {"Watch of Perfect Timing", "Ring", "+1 Dash",
     "It does not tell hours. It tells 'now is a good moment to go'."},
    {"Whistle of Start-Line Joy", "Relic", "+1 Speed",
     "One tweet and even shy feet remember they like races."},
    {"Cape-Pin of Afterimages", "Relic", "+2 Dash",
     "Leave a friendly ghost of yourself for anyone who needed a wave."},
    {"Charm of Spin-Dashes", "Relic", "+1 Dash",
     "A marble that rolls in your pocket when you are about to be brave."},
    {"Bracelet of Loop-de-Loops", "Ring", "+1 Speed",
     "Twists once around the wrist. Paths home grow extra interesting."},
    {"Seal of Unstoppable Kindness", "Relic", "+2 Happy",
     "Stamped in gold. Mean days bounce off and go think about it."},
    {"Cloud of Gentle Storms", "Cape", "+1 Spark",
     "A pocket-cloud that rains only on gardens and dusty windows."},
    {"Tear of Summer Lightning", "Necklace", "+2 Spark",
     "A drop of light caught in glass. It never startles the same twice."},
    {"Fan of Warm Fronts", "Weapon", "+1 Energy",
     "Waves heat toward whoever looks coldest in the room."},
    {"Umbrella of Happy Rain", "Shield", "+1 Guard",
     "Rain on it sounds like applause. The handle fits a VoltPet mouth."},
    {"Kite of High Voltage", "Relic", "+1 Spark",
     "Flies even indoors, just a little, when someone is proud of you."},
    {"Tabor of Far Thunder", "Weapon", "+1 Spark",
     "A small drum. Distant storms keep time if you are feeling lonely."},
    {"Prism of Storm-End Bows", "Relic", "+1 Happy",
     "Hold it after rain and a rainbow practices being extra."},
    {"Bottle of Bottled Breeze", "Relic", "+1 Dash",
     "Uncork for a tailwind. Recork politely; the breeze has places to be."},
    {"Charm of Safe Harbor", "Necklace", "+2 Guard",
     "Ships, kites, and worried thoughts all remember where to land."},
    {"Staff of Soft Hail", "Weapon", "+1 Spark",
     "Hail that turns to sugar-beads before it hits anyone's nose."},
    {"Mail of Quill-Knit", "Shield", "+2 Guard",
     "Woven from shed quills. It rustles like a hug made of sunshine."},
    {"Buckler of Puffed Cheeks", "Shield", "+1 Guard",
     "Inflates when you are startled, then winks as if it meant to."},
    {"Circlet of Brave Naps", "Helm", "+2 Energy",
     "Sleep in it and you wake ready, never groggy, always a little sparkly."},
    {"Ring of Second Chances", "Ring", "+1 Happy",
     "The band is a loop. So is trying again. Both are allowed."},
    {"Cloak of Motherly Static", "Cape", "+2 Guard",
     "Smells like clean laundry and far-off storms that already passed."},
    {"Boots of Finding Home", "Boots", "+1 Energy",
     "Left boot knows the way. Right boot knows the snacks."},
    {"Charm of Not-Alone", "Necklace", "+2 Happy",
     "Pulses once when a friend thinks of you, even from another town."},
    {"Shield of Shared Umbrellas", "Shield", "+1 Guard",
     "Grows a little wider if someone steps in from the rain."},
    {"Helm of Listening", "Helm", "+1 Find",
     "You hear what people meant, which is usually nicer than they said."},
    {"Aegis of Playground Rules", "Shield", "+2 Guard",
     "No hitting. Take turns. Share the sparkfruit. Enforced kindly."},
    {"Heart of Isle of Ring", "Relic", "+3 Happy",
     "A stone from the meadow that hums. VoltPets bow to it, then nap."},
    {"Crown of the First VoltPet", "Helm", "+2 Spark",
     "Too big for anyone proud. It fits perfectly if you offer to share."},
    {"Orb of World-Loop Dreams", "Relic", "+2 Dash",
     "Sleep with it and you race the whole world before breakfast."},
    {"Quill of Lasting Echo", "Weapon", "+2 Find",
     "Write a kind note and the paper keeps whispering it for days."},
    {"Ring of Trainer's Promise", "Ring", "+3 Happy",
     "A circle with no clasp. Promises made in it tend to keep themselves."},
    {"Cape of Horizon Spark", "Cape", "+2 Speed",
     "The hem is always a little ahead of you, pointing at the next good thing."},
    {"Blade of Kind Legends", "Weapon", "+2 Spark",
     "Heroes who carried it are remembered for picnics as much as quests."},
    {"Grail of Shared Snacks", "Relic", "+3 Snack",
     "Never empty if two creatures drink. Politeness is the other ingredient."},
    {"Star of Meadow Frequencies", "Necklace", "+3 Find",
     "A lucky star that fell as a radio whisper. It still winks on cue."},
    {"Relic of Forever Friends", "Relic", "+3 Happy",
     "The last treasure. It only appears for trainers who already knew."},
};

const vp_art_t *vp_art_get(unsigned id) {
    if (id >= VP_NART) return &vp_arts[0];
    return &vp_arts[id];
}
