#!/usr/bin/env python3
"""Embed a merged ESP32-C6 flash image for LanFerry to program over UART1.

The Bottlenose ROM download UART is GPIO16=TX / GPIO17=RX, which is swapped
relative to the app wiring, so the OG bit-bangs those pins. The blob is a
merged image at offset 0 (bootloader + partition table + app), produced by:

    esptool.py --chip esp32c6 merge_bin -o firmware/bottlenose/fwog_c6.bin \\
        --flash_mode dio --flash_freq 80m --flash_size 4MB \\
        0x0 bootloader.bin 0x8000 partition-table.bin 0x10000 fwog_bottlenose.bin
"""
from pathlib import Path
import argparse
import zlib


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--bin", type=Path, required=True)
    p.add_argument("--out-dir", type=Path, required=True)
    args = p.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    if args.bin.is_file() and args.bin.stat().st_size > 256:
        data = args.bin.read_bytes()
        src = args.bin.resolve().as_posix()
        size = len(data)
        crc = zlib.crc32(data) & 0xFFFFFFFF
        asm = (
            "/* Generated by tools/gen_c6_image.py. */\n"
            "    .section .rodata.fwog_c6_image, \"a\"\n"
            "    .balign 4\n"
            "    .global fwog_c6_image\n"
            "fwog_c6_image:\n"
            f"    .incbin \"{src}\"\n"
            "    .global fwog_c6_image_end\n"
            "fwog_c6_image_end:\n"
        )
    else:
        size = 0
        crc = 0
        asm = (
            "/* Generated by tools/gen_c6_image.py -- no fwog_c6.bin yet. */\n"
            "    .section .rodata.fwog_c6_image, \"a\"\n"
            "    .balign 4\n"
            "    .global fwog_c6_image\n"
            "fwog_c6_image:\n"
            "    .byte 0\n"
            "    .global fwog_c6_image_end\n"
            "fwog_c6_image_end:\n"
        )

    (args.out_dir / "c6_image.S").write_text(asm, encoding="ascii")
    (args.out_dir / "c6_image.c").write_text(
        "/* Generated by tools/gen_c6_image.py. */\n"
        "#include \"bottlenose/c6_image.h\"\n"
        f"const unsigned fwog_c6_image_size = {size}u;\n"
        f"const unsigned fwog_c6_image_crc  = 0x{crc:08X}u;\n",
        encoding="ascii",
    )
    print(f"c6 image: {size} bytes crc32 {crc:08X}")


if __name__ == "__main__":
    main()
