"""Emit the fwog_uf2_info_t record as a byte array, CRC already correct.

The record's trailing field is a CRC-32 over its own preceding 212 bytes, so
it cannot be written as a C initialiser: the value is not known until the
bytes are laid out. This script lays them out, CRCs them, and emits bytes.
That is also what lets the generator own the layout it computed over, rather
than trusting the compiler to reproduce it.

zlib.crc32 is byte-for-byte fwog_crc32(): poly 0x04C11DB7 reflected, init
0xFFFFFFFF, reflected in and out, final xor 0xFFFFFFFF. tools/genimage.py
documents the same equivalence for the same reason, and tests/test_uf2_info.c
asserts the C side, so a divergence cannot go unnoticed.

See bsp/common/uf2_info.h for what the record is for and why it is scanned
rather than pointed at.
"""
import argparse
import struct
import zlib

MAGIC0, MAGIC1 = 0x4F475746, 0x4F464E49   # "FWGO", "INFO"
STRUCT_VERSION = 1
NAME_LEN, DESC_LEN, BUILD_LEN = 32, 128, 32
SIZE = 216

# The 212 bytes the CRC covers. check_uf2_info.py calls the same string BODY
# and appends " I" for the full record; keep the two spellings identical.
BODY = "<II H B B H H {}s {}s {}s I".format(NAME_LEN, DESC_LEN, BUILD_LEN)


def fixed(s, n, what):
    """Encode `s` into exactly n bytes, NUL-padded, REFUSING to truncate.

    Truncating here would produce a record that passes every downstream check
    and says the wrong thing -- the worst available outcome. CMake already
    caps DESCRIPTION before we are called; this is the backstop for the other
    fields and for anyone invoking this script directly."""
    b = s.encode("ascii", "strict")
    if len(b) > n - 1:
        raise SystemExit(
            "gen_uf2_info: {} is {} bytes; the record holds {} plus a "
            "terminator".format(what, len(b), n - 1))
    return b + b"\x00" * (n - len(b))


def build_record(cpu, kind, version, name, description, build, build_ts):
    body = struct.pack(BODY, MAGIC0, MAGIC1, STRUCT_VERSION,
                       cpu, kind, version, 0,
                       fixed(name, NAME_LEN, "NAME"),
                       fixed(description, DESC_LEN, "DESCRIPTION"),
                       fixed(build, BUILD_LEN, "build"),
                       build_ts)
    assert len(body) == SIZE - 4, len(body)
    return body + struct.pack("<I", zlib.crc32(body) & 0xFFFFFFFF)


def emit(rec):
    rows = []
    for i in range(0, len(rec), 12):
        rows.append("    " + " ".join("0x%02X," % b for b in rec[i:i + 12]))
    return (
        "/* GENERATED by tools/gen_uf2_info.py. Do not edit.\n"
        " * See bsp/common/uf2_info.h for what this record is. */\n"
        '#include "common/uf2_info.h"\n'
        "\n"
        "/* Nothing in the firmware references this record -- a host scans the\n"
        " * flashed image for it. That makes surviving the link the whole\n"
        " * problem:\n"
        " *\n"
        " *   `used` stops the COMPILER dropping it. Necessary, not enough.\n"
        " *   `retain` was tried and is IGNORED by this toolchain\n"
        " *     (-Wattributes), so it bought nothing and is not used here.\n"
        " *   The section .binary_info.keep.* IS KEEP'd by the SDK's linker\n"
        " *     script, and was rejected: picotool walks\n"
        " *     __binary_info_start..__binary_info_end as an array of\n"
        " *     POINTERS, so 216 raw bytes there become 54 bogus ones.\n"
        " *\n"
        " * What actually holds it is -Wl,--undefined=fwog_uf2_info, added by\n"
        " * fwog_add_uf2_info(). GNU ld treats a --undefined symbol as a\n"
        " * garbage-collection ROOT, which is exactly what an unreferenced\n"
        " * record needs and costs no linker script change.\n"
        " *\n"
        " * NONE OF THAT IS PROOF. Only tools/check_uf2_info.py, which reads\n"
        " * the linked artefact, can show the record survived -- and it found\n"
        " * this exact failure once already. */\n"
        "__attribute__((used))\n"
        "const unsigned char fwog_uf2_info[%d] = {\n%s\n};\n"
        "\n"
        "/* The generator laid these bytes out; this is where that layout is\n"
        " * checked against the struct the firmware and tests compile. */\n"
        "_Static_assert(sizeof(fwog_uf2_info) == sizeof(fwog_uf2_info_t),\n"
        '               "generated UF2 info record disagrees with '
        'fwog_uf2_info_t");\n'
        % (len(rec), "\n".join(rows)))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", required=True)
    p.add_argument("--cpu", type=int, required=True,
                   help="0 = display, 1 = main")
    p.add_argument("--kind", type=int, required=True,
                   help="0 = application, 1 = bootloader")
    p.add_argument("--version", type=int, required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--description", required=True)
    p.add_argument("--build", default="",
                   help="git describe; EMPTY for display apps -- see "
                        "uf2_info.h")
    p.add_argument("--build-ts", type=int, default=0,
                   help="git commit epoch; 0 for display apps")
    a = p.parse_args()

    if a.cpu not in (0, 1):
        raise SystemExit("gen_uf2_info: --cpu must be 0 or 1")
    if a.kind not in (0, 1):
        raise SystemExit("gen_uf2_info: --kind must be 0 or 1")
    if not 0 <= a.version <= 999:
        raise SystemExit(
            "gen_uf2_info: --version %d is outside 000-999" % a.version)
    if not a.description:
        raise SystemExit("gen_uf2_info: --description must not be empty")
    # A display APPLICATION's bytes must be a pure function of its source: the
    # main-side updater skips the transfer by comparing the image CRC32, so a
    # build-varying byte forces a reflash on every commit. Refuse here as well
    # as in CMake, because this script can be called directly.
    #
    # kind is part of the condition, not decoration. The BOOTLOADER is also a
    # display-CPU binary, and it DOES carry build/build_ts: it is flashed by
    # UF2 and has no CRC-skip path, so its bytes changing costs nothing.
    if a.cpu == 0 and a.kind == 0 and (a.build or a.build_ts):
        raise SystemExit(
            "gen_uf2_info: a display APPLICATION record must carry no "
            "build/build_ts; they would change the image CRC32 every commit "
            "and force a reflash. See bsp/common/uf2_info.h. (The bootloader, "
            "kind=1, is exempt: it is UF2-flashed and has no CRC-skip path.)")

    rec = build_record(a.cpu, a.kind, a.version, a.name, a.description,
                       a.build, a.build_ts)
    with open(a.out, "w") as f:
        f.write(emit(rec))


if __name__ == "__main__":
    main()
