#!/usr/bin/env python3
"""Convert the OG Vegas PNG/WAV into display-CPU C assets."""

from pathlib import Path
import argparse
import struct
import wave

from PIL import Image, ImageOps


LCD_W = 320
LCD_H = 240
I2S_RATE = 8000

# NOT padded with trailing silence.
#
# An earlier version of this script padded the clip out to 12 s so the I2S
# state machine never ran dry, because a starved-but-running SM on this board
# re-shifts its last contents into an amplifier that has no shutdown line. The
# BSP now parks the state machine at end of playback (see
# bsp/display_cpu/audio/i2s_audio.h, trap 2), so the padding is dead weight:
# it was 79,400 zero samples, 83% of the array and about 290 KB of generated C.
#
# If a future change makes the driver stop parking, do not bring the padding
# back -- fix the driver.


def emit_array(out, c_type, name, values, per_line):
    out.write(f"const {c_type} {name}[] = {{\n")
    for i in range(0, len(values), per_line):
        row = values[i : i + per_line]
        out.write("    " + ", ".join(str(v) for v in row) + ",\n")
    out.write("};\n\n")


def convert_image(path):
    image = Image.open(path).convert("RGB")
    fitted = ImageOps.contain(image, (LCD_W, LCD_H), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", (LCD_W, LCD_H), "black")
    canvas.paste(fitted, ((LCD_W - fitted.width) // 2, (LCD_H - fitted.height) // 2))
    return [
        ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        for r, g, b in canvas.getdata()
    ]


def convert_audio(path):
    with wave.open(str(path), "rb") as wav:
        if (wav.getnchannels(), wav.getsampwidth(), wav.getframerate()) != (1, 2, 16000):
            raise ValueError("audio must be mono, 16-bit PCM at 16000 Hz")
        samples = struct.unpack(f"<{wav.getnframes()}h", wav.readframes(wav.getnframes()))
    # Box-filter each pair while decimating 16 kHz to the BSP driver's 8 kHz.
    audio = [(samples[i] + samples[i + 1]) // 2 for i in range(0, len(samples) - 1, 2)]
    # Nyquist here is 4 kHz (i2s_audio.h): content above it aliases audibly.
    # The box filter is a crude anti-alias, which is fine for a demo clip and
    # would not be for anything tonal.
    return audio


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("png", type=Path)
    parser.add_argument("wav", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    pixels = convert_image(args.png)
    audio = convert_audio(args.wav)
    with args.output.open("w", encoding="ascii", newline="\n") as out:
        out.write("/* Generated by tools/gen_ogvegas_assets.py. */\n")
        out.write('#include "ogvegas_assets.h"\n\n')
        emit_array(out, "uint16_t", "ogvegas_image", pixels, 12)
        out.write(f"const unsigned ogvegas_image_pixels = {len(pixels)}u;\n\n")
        emit_array(out, "int16_t", "ogvegas_audio", audio, 12)
        out.write(f"const unsigned ogvegas_audio_samples = {len(audio)}u;\n")


if __name__ == "__main__":
    main()
