#!/usr/bin/env python3
"""genimage - embed a display-CPU application into the main-CPU binary.

Reads a display app's .bin and emits two sources for main to compile:

  display_image.S   .incbin of the raw bytes, into main's flash
  display_image.c   size, CRC32, build timestamp, version string

The blob lives in main's flash and costs no RAM: main streams it straight
out of XIP to the display over the link.

.incbin rather than a C array of hex bytes, because a 500 KB image is a
3 MB source file and the cross-compiler would re-parse it on every build.

The output is a pure function of its inputs -- notably the build timestamp
is the .bin's mtime, NOT the wall clock. A generator whose output changed
every run would relink main on every build and defeat CMake's dependency
tracking, for a field nobody reads programmatically.
"""
import argparse
import os
import pathlib
import zlib

# Longest version string fwog_app_meta_t.version can hold, minus the NUL.
# Keep in step with FWOG_APP_VERSION_LEN in bsp/common/app_meta.h.
VERSION_MAX = 31


def crc32_ieee(data):
    """CRC-32/IEEE, byte-for-byte identical to fwog_crc32() in bsp/common/crc.c.

    zlib.crc32 is the same parameterisation -- poly 0x04C11DB7 reflected,
    init 0xFFFFFFFF, reflected in and out, final xor 0xFFFFFFFF -- which is
    why no hand-rolled table lives here. tests/test_image_crc.c and
    tools/tests/test_genimage.py assert the same check values against the C
    and Python sides so a divergence cannot go unnoticed."""
    return zlib.crc32(data) & 0xFFFFFFFF


def sanitize_version(s):
    """Make `s` safe to paste into a C string literal and short enough to fit.

    Truncation matters: `git describe` on a tagged build easily exceeds 31
    characters, and an over-long initializer for char[32] is a compile
    error, not a silent truncation."""
    s = (s or "").strip()
    if not s:
        s = "dev"
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    # Drop anything that would end the line or confuse a terminal.
    s = "".join(c for c in s if 0x20 <= ord(c) < 0x7F)
    return s[:VERSION_MAX]


def build_ts(path):
    """Unix seconds for the image, taken from the .bin's mtime."""
    return int(os.path.getmtime(path))


def render_asm(bin_path):
    """The .incbin wrapper.

    The path is absolute with forward slashes: the assembler resolves a
    relative .incbin against its own working directory and -I list, which
    is not where CMake put the .bin. Forward slashes are accepted by
    arm-none-eabi-as on Windows."""
    p = pathlib.Path(bin_path).resolve().as_posix()
    return (
        "/* Generated by tools/genimage.py -- do not edit. */\n"
        "    .section .rodata.fwog_display_image, \"a\"\n"
        "    .balign 4\n"
        "    .global fwog_display_image\n"
        "fwog_display_image:\n"
        f"    .incbin \"{p}\"\n"
        "    .global fwog_display_image_end\n"
        "fwog_display_image_end:\n"
    )


def render_c(size, crc, ts, version):
    """The identity record. Designated initializers, so a field reordered in
    display_image.h cannot silently shift the values."""
    return (
        "/* Generated by tools/genimage.py -- do not edit. */\n"
        "#include \"display_update/display_image.h\"\n"
        "\n"
        "const fwog_display_image_info_t fwog_display_image_info = {\n"
        f"    .size     = {size}u,\n"
        f"    .crc32    = 0x{crc:08X}u,\n"
        f"    .build_ts = {ts}u,\n"
        f"    .version  = \"{version}\",\n"
        "};\n"
    )


def generate(bin_path, out_dir, version):
    """Write both files. Returns (size, crc, ts, version)."""
    data = pathlib.Path(bin_path).read_bytes()
    if not data:
        raise ValueError(f"{bin_path} is empty -- did the display app link?")
    size = len(data)
    crc = crc32_ieee(data)
    ts = build_ts(bin_path)
    ver = sanitize_version(version)

    out = pathlib.Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "display_image.S").write_text(render_asm(bin_path))
    (out / "display_image.c").write_text(render_c(size, crc, ts, ver))
    return size, crc, ts, ver


def main(argv=None):
    p = argparse.ArgumentParser(prog="genimage")
    p.add_argument("--bin", required=True, help="display app .bin")
    p.add_argument("--out-dir", required=True)
    p.add_argument("--version", default="dev")
    a = p.parse_args(argv)
    size, crc, ts, ver = generate(a.bin, a.out_dir, a.version)
    print(f"display image: {size} bytes, crc32 {crc:08X}, ts {ts}, "
          f"version {ver}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
